django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views
from equ.forms import CustomLoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('equ.urls')),
    path('login/', auth_views.LoginView.as_view(authentication_form=CustomLoginForm,
        template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

django_project/equ/urls.py
from django.urls import path
from django.contrib import admin
from . import views

urlpatterns = [
    path('', views.user_redirect, name='user_redirect'),
    path('register/', views.register, name='register'),
    path('registration_pending/', views.view_pending_requests, name='registration_pending'),
    path('approve_request/<int:request_id>/', views.approve_request, name='approve_request'),
    path('reject_request/<int:request_id>/', views.reject_request, name='reject_request'),
    path('register_super_admin/', views.register_super_admin, name='register_super_admin'),
    path('a_overview/',views.a_overview,name="a_overview"),
    path('a_members/',views.a_members,name="a_members"),
    path('a_member_detail/<int:pk>/', views.a_member_detail, name='a_member_detail'),
    path('a_equipment/',views.a_equipment,name="a_equipment"),
    path('a_add_equipment/', views.a_add_equipment, name='a_add_equipment'),
    path('a_remove_equipment/<int:pk>/', views.a_remove_equipment, name='a_remove_equipment'),
    path('a_materials/',views.a_materials,name="a_materials"),
    path('a_add_category/', views.a_add_category, name='a_add_category'),
    path('a_remove_category/<int:pk>/', views.a_remove_category, name='a_remove_category'),
    path('a_category_detail/<int:pk>/', views.a_category_detail, name='a_category_detail'),
    path('a_add_material/<int:pk>/', views.a_add_material, name='a_add_material'),
    path('a_add_stock/<int:material_pk>/<int:category_pk>/', views.a_add_stock, name='a_add_stock'),
    path('a_activity/',views.a_activity,name="a_activity"),
    path('a_activity_project_requests/',views.a_activity_project_requests,name="a_activity_project_requests"),
    path('a_activity_material_requests/',views.a_activity_material_requests,name="a_activity_material_requests"),
    path('a_activity_past_due/',views.a_activity_past_due,name="a_activity_past_due"),
    path('a_activity_early_collection/',views.a_activity_early_collection,name="a_activity_early_collection"),
    path('a_project_detail/<int:pk>/', views.a_project_detail, name='a_project_detail'),
    path('a_material_request_handling/<int:pk>/', views.a_material_request_handling, name='a_material_request_handling'),
    path('a_confirmed_project_detail/<int:pk>/', views.a_confirmed_project_detail, name='a_confirmed_project_detail'),
    path('u_confirmed_project_detail/<int:pk>/', views.u_confirmed_project_detail, name='u_confirmed_project_detail'),
    path('c_list_superadmin/<int:pk>/',views.c_list_superadmin,name="c_list_superadmin"),
    path('c_list/',views.c_list,name="c_list"),
    path('u_projects/',views.u_projects,name="u_projects"),
    path('u-projects-confirmed/', views.u_projects_confirmed, name='u_projects_confirmed'),
    path('u-projects-pending/', views.u_projects_pending, name='u_projects_pending'),
    path('u-projects-notifications/', views.u_projects_notifications, name='u_projects_notifications'),
    path('u_help/',views.u_help,name="u_help"),
    path('u_inventory/',views.u_inventory,name="u_inventory"),
    path('u_inventory_category/',views.u_inventory_category,name="u_inventory_category"),
    path('inventory/active/', views.u_inventory_active, name='u_inventory_active'),
    path('inventory/pending/', views.u_inventory_pending, name='u_inventory_pending'),
    path('inventory/closed/', views.u_inventory_closed, name='u_inventory_closed'),
    path('u_request_material/<int:pk>/',views.u_request_material,name="u_request_material"),
    path('u_profilepage/', views.u_profile_page, name='u_profile_page'),
    path('s_overview/', views.s_overview, name='s_overview'),
    path('s_labs/', views.s_labs, name='s_labs'),
    path('s_lab_detail/<int:pk>/', views.s_lab_detail, name='s_lab_detail'),
    path('s_member_detail/<int:pk>/', views.s_member_detail, name='s_member_detail'),
    path('s_confirmed_project_detail/<int:pk>/', views.s_confirmed_project_detail, name='s_confirmed_project_detail'),
    path('s_admins/<int:pk>/', views.s_admins, name='s_admins'),
    path('s_equipment/', views.s_equipment, name='s_equipment'),
    path('u_create_project/', views.u_create_project, name='u_create_project'),
    path('u_project_detail/<int:pk>/', views.u_project_detail, name='u_project_detail'),
    path('c_m1/<int:pk>/', views.c_m1, name='c_m1'),
    path('c_m2/<int:pk>/', views.c_m2, name='c_m2'),
    path('c_m3/<int:pk>/', views.c_m3, name='c_m3'),
    path('u_confirmed_project_detail/<int:pk>/', views.u_confirmed_project_detail, name='u_confirmed_project_detail')
]

django_project/equ/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Organisation(models.Model):
    name = models.CharField(max_length=100)
    super_admin = models.ForeignKey(
        User,
        limit_choices_to={'groups__name': 'superadmin'},
        null=True, 
        on_delete=models.CASCADE,
    )
    organisation_id = models.IntegerField(null=True)
    description = models.TextField(null=True)  # Nullable field
    contact_person = models.CharField(max_length=100, null=True)  # Nullable field
    contact_email = models.EmailField(null=True)  # Nullable field
    contact_phone = models.CharField(max_length=20, null=True)  # Nullable field
    street_address = models.CharField(max_length=255, null=True)  # Nullable field
    city = models.CharField(max_length=100, null=True)  # Nullable field
    state_province = models.CharField(max_length=100, null=True)  # Nullable field
    postal_code = models.CharField(max_length=20, null=True)  # Nullable field
    country = models.CharField(max_length=100, null=True)  # Nullable field

    def __str__(self):
        return self.name
class RegistrationRequest(models.Model):
    username = models.CharField(max_length=150)
    email = models.EmailField()
    # Add other fields as needed
    status = models.CharField(max_length=20, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')

    def __str__(self):
        return self.username

class Lab(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250,null=True)
    lab_admin = models.ForeignKey(
        User,
        limit_choices_to={'groups__name': 'admin'},
        null=True,  # Set the default value to None
        on_delete=models.CASCADE,
        related_name='lab_admin_of'
    )

    def __str__(self):
        return self.name


class Profile(models.Model):
    USER_TYPES = [
        ('Student', 'Student'),
        ('Professor', 'Professor'),
        ('Technician', 'Technician'),
        ('Other', 'Outsider'),
    ]

    MACHINE_CHOICES = [
        ('Yes', 'Yes'),
        ('No', 'No'),
    ]

    HOW_HEARD_CHOICES = [
        ('Peers', 'Peers'),
        ('Faculty', 'Faculty'),
        ('Technicians', 'Technicians'),
        ('Social Media', 'Social Media'),
        ('Campus Communication', 'Campus Communication'),
        ('Others', 'Others'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE, null=True)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE, null=True)
    user_type = models.CharField(max_length=20, choices=USER_TYPES)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=20)
    email = models.EmailField()
    branch = models.CharField(max_length=100)
    year_of_graduation = models.PositiveIntegerField(blank=True, null=True)
    institute_name = models.CharField(max_length=100)
    training_record = models.CharField(max_length=3, choices=MACHINE_CHOICES)
    machines_trained_in = models.CharField(max_length=200, blank=True)
    how_heard_about = models.CharField(max_length=50, choices=HOW_HEARD_CHOICES, blank=True, null=True)



class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=400)
    lab = models.ForeignKey('Lab', on_delete=models.CASCADE, related_name='projects')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now) 

    def __str__(self): 
        return self.name



class Equipment(models.Model):
    CONDITION_CHOICES = [
        ('Excellent', 'Excellent'),
        ('Good', 'Good'),
        ('Poor', 'Poor'),
        ('Bad', 'Bad'),
    ]
    name = models.CharField(max_length=100)
    lab = models.ForeignKey('Lab', on_delete=models.CASCADE, related_name='equipments')
    condition = models.CharField(max_length=20, choices=CONDITION_CHOICES, default='Good')
    
    def __str__(self):
        return self.name
    

    
class Booking(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True,default=None)

    def __str__(self):
        return f'{self.start_time} - {self.end_time} for {self.equipment}'
    

class Confirmed_Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=400)
    lab = models.ForeignKey('Lab', on_delete=models.CASCADE, related_name='confirmed_projects')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now) 

    def __str__(self): 
        return self.name
    
class Confirmed_Booking(models.Model): 
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    project = models.ForeignKey(Confirmed_Project, on_delete=models.CASCADE, null=True, blank=True,default=None)

    def __str__(self):
        return f'{self.start_time} - {self.end_time} for {self.equipment}'
    
class Archived_Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=400)
    lab = models.ForeignKey('Lab', on_delete=models.CASCADE, related_name='archived_projects')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now) 

    def __str__(self): 
        return self.name
    

class Archived_Booking(models.Model): 
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now) 
    project = models.ForeignKey(Archived_Project, on_delete=models.CASCADE, null=True, blank=True,default=None)

    def __str__(self):
        return f'{self.start_time} - {self.end_time} for {self.equipment}'
    
class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message
    
class UserActivityLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    login_time = models.DateTimeField()
    logout_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.login_time}"

class Category(models.Model):
    name = models.CharField(max_length=100)
    lab = models.ForeignKey(Lab,on_delete=models.CASCADE)

  
class Material(models.Model):
    stock = models.IntegerField(null=True,blank=True)
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,blank=True, null=True)

    def __str__(self):
        return self.name
    
class Material_Request(models.Model):
    REQUEST_TYPES = [
        ('_', '_'),
        ('Borrow', 'Borrow'),
        ('Issue', 'Issue'),
    ]

    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(null=True, blank=True)
    request_type = models.CharField(max_length=10, choices=REQUEST_TYPES)
    return_date = models.DateField(null=True, blank=True)  # Set only for issue requests
    status = models.IntegerField(default=0) #0-pending, 1-active, 2-closed
    user = models.ForeignKey(User,on_delete=models.CASCADE)

django_project/equ/templates/equ/a_activity_early_collection.html
{% extends "equ/a_activity.html" %}
{% block activitycontent %}    

<style>
  .el_col{
    background-color: #6897f5;
  border:1px solid #6897f5;
    color: white;
  }
  .proj_req{
  background-color: white;
    color: var(--primary);
}

.dpn{
  display: none;
}

.main-navbar{
  justify-content: end;
  height: max-content;
}
</style>

<!-- <h1> Early Collection </h1> -->
<ul class="project_list">
  {% for req in material_requests %}
  <li><form method="post" class="action-form" action="{% url 'a_material_request_handling' req.pk %}">
    {% csrf_token %}
    {{ req.quantity }} {{ req.material.name }} by User {{ req.user.username }}
    {% if req.request_type == 'Borrow' %}
    which was to be returned by {{ req.return_date }}
    {% endif %}
    
    <button type="submit" name="action" value="collect_early" class="a-actionbutton accept">Collected</button></form>
  </li>
  {% empty %}
    <li>No Requests found.</li>
  {% endfor %}
</ul>

{% endblock activitycontent %}   

django_project/equ/templates/equ/a_add_stock.html
{% extends "equ/a_base.html" %}
{% block content %}    

<style>
  .dpn{
    display: none;
  }
  
  .main-navbar{
    justify-content: end;
    height: max-content;
  }

  .my_projects{
    border: 1px solid lightgray;
    border-radius: 20px;
  }

  .materials span{
    border: 1px solid #6897f5;
    background-color: #6897f5;
  }

  .materials li{
    /* background-image: linear-gradient(to right, #60B8CA, #5890F9); */
    background: #ededed;
  }
</style>

<div class="my_projects">
  <h2>Modify Stock for {{ material.name }}</h2>
  <form method="post" style="margin-top: 10px;">
    {% csrf_token %}
    <label for="stock">Amount:</label>
    <input type="number" id="stock" name="stock" required>
    <button type="submit" name="modify" class="btn-uproject">Change</button>
  </form>
  <form method="post" style="margin-top: 1rem;">
    {% csrf_token %}
    <button type="submit" name="delete" class="btn-uproject" style="background: #fc716b;">Delete Material</button>
  </form>
{% endblock content %}   

django_project/equ/templates/equ/a_base.html
<!-- This File contains all the common code that I want to be inherited by all my webpages--> 

{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/u_inventory.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/a_overview.css' %}">
  
</head>
<body>
  <div class="container rcntc">
        <div class="sidebar">
          <ul>
            {% if user.is_authenticated %}
            <div class="mslogo"><img src="{% static 'images/MSClogo2.png' %}" alt="">
              <a> Lab ID: {{ user.username }}</a>
            </div> 
            <!-- <div class="mslogo"><img src="{% static 'images/MSClogo2.png' %}" alt=""></div> -->
            <a href="{% url 'a_overview' %}" class="overview"><div class="link"><span></span><li>
              <img src="{% static 'images/overview icon.png' %}" alt=""> Overview</li></div></a>
            <a href="{% url 'a_members' %}" class="members"><div class="link"><span></span><li>
              <img src="{% static 'images/members icon.png' %}" alt="">Members</li></div></a>
            <a href="{% url 'a_equipment' %}" class="equipment"><div class="link"><span></span><li>
              <img src="{% static 'images/equipments icon.png' %}" alt="">Equipment</li></div></a>
            <a href="{% url 'a_materials' %}" class="materials"><div class="link"><span></span><li>
              <img src="{% static 'images/inventory icon.png' %}" alt="">Inventory</li></div></a>
            <a href="{% url 'a_activity_project_requests' %}" class="activityLog"><div class="link"><span></span><li><img src="{% static 'images/activitylog icon.png' %}" alt="">Activity Log</li></div></a>
            <a href="{% url 'logout' %}" class="logout"><div class="link"><span></span><li>Log Out</li></div></a>
            
            {% else %}
            <a href="{% url 'login' %}" class="login"><div class="link"><span></span><li>Log In</li></div></a>
            {% endif %}
          </ul>
        </div>
      
        <div class="content acon">
          <!-- Add the nav bar -->
   <div class="main-navbar">
    <div class="cloudlogo dpn">
      <div class="cloud"><img src="{% static 'images/cloudavt.png' %}" alt=""></div>
      <span style="font-weight: bold;">Hello, {{ profile.first_name }}, Let's Manage!</span>
    </div>
    <a class="profile-link" href="{% url 'u_profile_page' %}">
      <button class="profile-button">{{ profile.first_name }}</button>
    </a>
  </div>
          {% block content %}
          {% endblock %}
        </div>
  </div>

  </body>
</html>

django_project/equ/templates/equ/a_overview.html
{% extends "equ/a_base.html" %}
{% block content %}    
{% load static %}
<style>
    .graph-image {
      width: 100%;
    height: 90%;
    /* object-fit: contain; */
    border-radius: 10px;
    }

    .overview span{
      border: 1px solid #6897f5;
    background-color: #6897f5;
    }

    .overview li{
      /* background-image: linear-gradient(to right, #60B8CA, #5890F9); */
    background: #ededed;
    }
    .actcard {
  border: 1px solid #ddd;
  border-radius: 5px;
  padding: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  background-color: #fff;
  color: #333;
  font-size: 16px;
  margin-bottom: 10px;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
  </style>
<div class="my_projects u_inventory">
  <div class="rq_items cpr">
    <a href="{% url 'c_list' %}" class="btn-uproject rqa"><img src="{% static 'images/viewcalendaricon.png' %}" alt=""> View Calendar</a>
    <a href="{% url 'a_activity_project_requests' %}" class="btn-uproject rqa"><img src="{% static 'images/managebookingsicon.png' %}" alt="" style="width: 30px;"> Manage Bookings</a>
    <a href="{% url 'a_activity_material_requests' %}" class="btn-uproject rqa"><img src="{% static 'images/manageitemsicon.png' %}" alt="">Manage Items</a>
  
  </div>
    <!-- <h1>Lab :{{lab.name}}</h1> -->
    <!-- <h2>Admin :{{lab.lab_admin}}</h2> -->
    <div class="mp1">
        <!-- <div class="clndr"><a href="{% url 'c_list' %}" class="btn btn-primary">View Calendar</a></div> -->
        <!-- <h2> Active Users: {{active_user_count}}</h2> -->

        <div class="graph">
          <div class="st">User Footfall</div>
          <img src="data:image/png;base64,{{ graph }}" alt="Daily Footfall Graph" class="graph-image">
        </div>
        <div class="status_up">
          <div class="status">
            <div class="st">Status</div>
            <div class="allst">
              <div class="sts">
                <div class="num">07</div>
                <p>Pending Booking Requests</p>
                <a href="#">view all</a>
              </div>
              <div class="sts">
                <div class="num">10</div>
                <p>Pending Item Requests</p>
                <a href="#">view all</a>
              </div>
              <div class="sts">
                <div class="num">03</div>
                <p>Active Users & Equipments</p>
                <a href="#">view all</a>
              </div>
            </div>
          </div>
          <div class="up">
            <div class="st">Upcomings</div>
            <div class="allst allup">
              <div class="sts">
                <img src="{% static 'images/up1.jpg' %}" alt="">
                <a href="#"> view all</a>
              </div>
              <div class="sts sts2">
                <img src="{% static 'images/up2.jpg' %}" alt="">
                <a href="#"> view all</a>
              </div>
            </div>
          </div>
        </div>
      
      <!-- <div class="actcard"> -->
        <!-- <div class="atcd">{{material_requests_count}} Pending Material Requests</div>
        <a href="{% url 'a_activity_material_requests' %}">Check</a>
      </div>
      <br> -->
      
      <!-- <div class="actcard">
        <div class="atcd">{{project_requests_count}} Pending Project Requests</div>
        <a href="{% url 'a_activity_project_requests' %}">Check</a>
      </div> -->


</div>
</div>
  

{% endblock content %}   

django_project/equ/templates/equ/c_m2.html
{% extends "equ/c_base.html" %}
{% block content %}    


<div class="al">
    <div class="calendar">
        <h3> Equipment Calendar for {{equipment.name}}</h3> 
    
    <div class="table_con">
        <table class="cal">
            <tr>
                <th class="t_d">Time/Date</th>
                {% for date in date_range %}
                    <th>{{ date|date:"jS F" }}</th>
                {% endfor %}
            </tr>
            {% for time_slot_range in time_slot_ranges %}
                {% with time_slot_start=time_slot_range.0 time_slot_end=time_slot_range.1 %}
                <tr>
                    <th>{{ time_slot_start|time:"h A" }} to {{ time_slot_end|time:"h A" }}</th>
                    {% for date in date_range %}
                    <td class="{% for booking in bookings %}{% if booking.start_time.date == date and booking.start_time.time <= time_slot_start.time and booking.end_time.time > time_slot_start.time %}Booked{% endif %}{% endfor %}">
                        &nbsp;
                    </td>
                    {% endfor %}
                </tr>
                {% endwith %}
            {% endfor %}
        </table>
    </div>
    </div>
</div>
{% endblock content %} 

django_project/equ/templates/equ/c_m3.html
{% extends "equ/c_base.html" %}
{% block content %}    


<div class="al">
    <div class="calendar">
        <h3> Equipment Calendar for {{equipment.name}}</h3> 
    
    <div class="table_con">
        <table class="cal">
        <tr>
            <th class="t_d"> Time/Date</th>
            {% for date in date_range %}
                <th>{{ date|date:"jS F" }}</th>
            {% endfor %}
        </tr>
        {% for time_slot_range in time_slot_ranges %}
            {% with time_slot_start=time_slot_range.0 time_slot_end=time_slot_range.1 %}
            <tr>
                <th>{{ time_slot_start|time:"h A" }} to {{ time_slot_end|time:"h A" }}</th>
                {% for date in date_range %}
                <td class="{% for booking in bookings %}{% if booking.start_time.date == date and booking.start_time.time <= time_slot_start.time and booking.end_time.time > time_slot_start.time %}Booked{% endif %}{% endfor %}">
                    &nbsp;
                </td>
                {% endfor %}
            </tr>
            {% endwith %}
        {% endfor %}
    </table>
    </div>
    </div>
</div>
{% endblock content %} 

django_project/equ/templates/equ/create_project.html
{% extends "equ/baseuser.html" %}
{% block content %}    

<form method="post">
    {% csrf_token %}
    <div>
      <label for="id_name">Project Name:</label>
      <input type="text" id="id_name" name="name" required>
    </div>
    <div>
      <label for="id_description">Description:</label>
      <textarea id="id_description" name="description" required></textarea>
    </div>
    <button type="submit">Create Project</button>
  </form>
  

{% endblock content %}   

django_project/equ/templates/equ/help.html
{% extends "equ/baseuser.html" %}
{% block content %}    


<h1>Help Blogs</h1>


  

{% endblock content %}   

django_project/equ/templates/equ/s_base.html
<!-- This File contains all the common code that I want to be inherited by all my webpages--> 

{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/u_inventory.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/a_overview.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/superadmin.css' %}">
</head>
<body>
  
  {% if user.is_authenticated %}
     
  <div class="container rcntc">
        <div class="sidebar">
          <ul>
            <div class="mslogo"><img src="{% static 'images/MSClogo2.png' %}" alt=""> <a> Lab ID: {{ user.username }}</a></div>
            <a href="{% url 's_overview' %}" class="overview"><div class="link"><span></span><li>
              <img src="{% static 'images/overview icon.png' %}" alt="">Overview</li></div></a>
            <a href="{% url 's_labs' %}" class="projects"><div class="link"><span></span><li>
              <img src="{% static 'images/administration.png' %}" alt="">Manage</li></div></a>
            <!-- <a href="{% url 'admin:index' %}" class="data"><div class="link"><span></span><li>Data</li></div></a> -->
            <a href="{% url 'logout' %}" class="logout"><div class="link"><span></span><li>Log Out</li></div></a>
            <!-- <li><a href="{% url 's_overview' %}">Overview</a></li>
            <li><a href="{% url 's_labs' %}">Projects</a></li> -->
            <!--<li><a href="{% url 's_equipment' %}">Equipments</a></li>-->
            <!-- <li><a href="{% url 'admin:index' %}">Data</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li> -->
            {% else %}
            <a href="{% url 'login' %}" class="login"><div class="link"><span></span><li>Log In</li></div></a>
            {% endif %}
          </ul>
        </div>
      
        <div class="content">
          <!-- Add the nav bar -->
     <div class="main-navbar">
      <div class="cloudlogo dpn">
        
        <div class="cloud"><img src="{% static 'images/cloudavt.png' %}" alt=""></div>
        <span>Hello, {{ user.username }}</span>
      </div>
      <a class="profile-link" href="#">
        <button class="profile-button">{{ user.username }}</button>
      </a>
    </div>

          {% block content %}
          {% endblock %}
        </div>
  </div>

  </body>
</html>

django_project/equ/templates/equ/s_confirmed_project_detail.html
{% extends "equ/s_base.html" %}
{% block content %}

<style>
    .projects span{
        border: 1px solid #6897f5;
    background-color: #6897f5;
    }

    .projects li{
      /* background-image: linear-gradient(to right, #60B8CA, #5890F9); */
      background: #ededed;
    }

    .dpn{
  display: none;
}

.main-navbar{
  justify-content: end;
  height: max-content;
}
</style>
  <div class="project-details">
    <h1>Project Details</h1>
    <br>
    <div class="project-info">
      <p><strong>Name:</strong> {{ project.name }}</p>
      <p><strong>Description:</strong> {{ project.description }}</p>
      <p><strong>Lab:</strong> {{ project.lab }}</p>
      <p><strong>User:</strong> {{ project.user }}</p>
      <p><strong>Duration:</strong> {{ project.start_date }} to {{ project.end_date }}</p>
    </div>
    <br>
    <h2>Equipments:</h2>
    <div class="equipment-list">
      {% for booking in bookings %}
      <div class="booking">
        <p class="equipment-name">{{ booking.equipment }}</p>
        <p class="booking-details">
          Booking from {{ booking.start_time }} to {{ booking.end_time }} 
        </p>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}